core/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from django.contrib.auth.views import login
from django.contrib import auth
import biblioteca.views

from django.conf import settings
from django.conf.urls.static import static

from django.db.models import Q

from django.contrib.auth.views import password_change

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', biblioteca.views.HomeView.as_view(), name = "home"),
    #hace busqueda
    url(r'^busqueda/$', biblioteca.views.Busqueda.as_view(), name = "busqueda"),
    #listar cosas
    url(r'^libros/$', biblioteca.views.LibrosListView.as_view(), name = "libros"),
    url(r'^libros-en/(?P<pk>(\d{0,3}))/$', biblioteca.views.LibroInCasilleroListView.as_view(), name ="libroscas"),
    url(r'^casilleros/$', biblioteca.views.CasillerosListView.as_view(), name = "casilleros"),
    url(r'^mis-libros/$', biblioteca.views.MyBooksListView.as_view(), name="propios"),
    url(r'^usuarios/$', biblioteca.views.UsuariosListView.as_view(), name="usuarios"),
    url(r'^biblioteca/(?P<usuario>\w+)$', biblioteca.views.PersonBooksListView.as_view(), name="biblioteca-user"),
    #Cambiar libros
    url(r'^prestar/(?P<identificador>\d+)/$', biblioteca.views.prestar, name = "prestar"),
    url(r'^devolver/(?P<identificador>\d+)/$', biblioteca.views.devolver, name = "devolver"),
    url(r'^biblioteca/prestar/(?P<identificador>\d+)/(?P<usuario>\w+)/$', biblioteca.views.prestar_administrador, name = "biblioteca-prestar"),
    #crear cosas
    url(r'^nuevo-libro/$', biblioteca.views.LibroCreateView.as_view(), name="nuevoLibro"),
    url(r'^nuevo-casillero/$', biblioteca.views.crear_casillero, name = "casillero-nuevo"),
    url(r'^login/$', biblioteca.views.login_user, name = "login"),
    url(r'^logout/$', auth.views.logout, name = "logout"),
    url(r'^all/$', biblioteca.views.LibrosListView.as_view(), name = "allbooks"),

    url(r'^labels/', include('labels.urls')),
    url(r'^design/', biblioteca.views.DesignLabels, name = "design"),
    #Editar libros
     url(r'edit/(?P<identificador>\d+)/?$', biblioteca.views.LibroUpdateView.as_view(), name="editar" ),
    url(r'^cambiar-contraseña/$', password_change, {'template_name': 'password_change_form.html','post_change_redirect': '/'}, name="password-change"),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

labels/urls.py
from django.conf.urls import include, url
from labels.forms import TagForm
from labels.models import Tag

from django import forms


from labels import views as views



urlpatterns = [
    url(r'new/$', views.new),

    url(r'edit/(?P<pk>\d+)/?$', views.ListUpdate.as_view() ),
    url(r'delete/(?P<pk>\d+)/?$', views.ObjDelete.as_view() ),

    url(r'print/(?P<tag_id>\d+)/(?P<type>\w+)/$', views.print_pdf),
    url(r'^$', views.list.as_view(), name= "labels")
]

labels/models.py
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver

class Tag(models.Model):
    name = models.CharField(max_length=100, blank=True)
    slogan1 = models.CharField(max_length=100, blank=True)
    slogan2 = models.CharField(max_length=100, blank=True)
    contact1 = models.CharField(max_length=100, blank=True)
    contact2 = models.CharField(max_length=100, blank=True)
    contact3 = models.CharField(max_length=100, blank=True)
    url = models.URLField(max_length=100, blank=True)
    logo = models.ImageField(upload_to='media/images/logos', blank="True")
    qrcode = models.ImageField(upload_to='media/images/qrcodes', blank="True")
    #version = models.ForeignKey('TagVersion', blank=True, null=True)
    author = models.CharField(max_length=100, blank=True)
    template = models.CharField(max_length=100, blank=True)
    entered = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class TagVersion(models.Model):
    tag = models.ForeignKey(Tag)
    version_num = models.PositiveIntegerField(blank=True)
    entered = entered = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s v%s" %(self.tag.name, self.version_num)

@receiver(post_save, sender=Tag)
def tag_save_handler(sender, **kwargs):
    # Check to see if tag already exits
    tag = kwargs['instance']
    tv = TagVersion.objects.filter(tag=tag)
    if tv:
        # Add a new version
        tv = tv[0]
        version_num = tv.version_num + 1
    else:
        # Create a new version
        version_num = 1
    tv = TagVersion(version_num=version_num, tag=tag)
    tv.save()

labels/forms.py
from django.forms import ModelForm
from labels.models import Tag
from formtools.preview import FormPreview
from django.http import HttpResponseRedirect, HttpResponse


class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'

labels/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from biblioteca.models import Impresion
from .models import Tag
from labels.forms import TagForm
from django.template import RequestContext

from django.http import HttpResponse, HttpResponseRedirect

from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView

from django.core.urlresolvers import reverse_lazy


#show all the tags
class list(ListView):
    model = Tag

#Delete an object tag
class ObjDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('home')

#update a object
class ListUpdate(UpdateView):
    model = Tag
    form_class = TagForm
    template_name = 'labels/tag_form.html'
    success_url = reverse_lazy('home')

def new(request):
    if request.method == 'POST':
        form = TagForm(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect(reverse_lazy("home"))

    else:
       form = TagForm()

    return render('labels/tag_form.html', {'form':form},context_instance=RequestContext(request) )

def print_pdf(request, tag_id, type):
    from reportlab.pdfgen.canvas import Canvas
    from labels.pdf_templates import LabelPDF
    #Letter is a paper format, you can import A4 for example
    from reportlab.lib.pagesizes import A4

    tag = get_object_or_404(Impresion, pk=tag_id)

    #name of the pdf
    fname = "mylabels.pdf"
    #Generating response for file
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=%s' %(fname)

    #creating the canvas object. You can change "letter" with another paper type
    c  = Canvas(response, pagesize=A4)
    #LabelPDF is the class in pdf_templates that draws on the pdf
    pdf = LabelPDF(tag,type)
    #pdf.showBoundary=1  # Turns this on for debugging purposes.
    c = pdf.draw_frames(c)
    c.save()

    return response

    tv = {'tag_id':tag_id}
    return render("labels/print.html",tv)

templates/labels/nav_bar.html
{% block nav_bar %}
<a href="/labels/list/">List</a> |
<a href="/labels/new/">Create New</a>
{% endblock %}

templates/labels/print.html
{% extends "base.html" %}

{% block content %}
  <p>Print tags for {{tag_id}}</p>
{% endblock %}

templates/labels/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
Are you sure you want to delete this <strong>{{object.name}}</strong>?
<form action="/labels/delete/{{object.id}}/" method="POST">{% csrf_token %}
<input type="submit" value="Delete"/>
</form>

<form action="/labels/list/" method="GET">
<input type="submit" value="Cancel"/>
</form>
{% endblock %}

templates/labels/tag_form.html
{% extends "base.html" %}
{% block content %}
{% include "labels/nav_bar.html" %}
<h2>Create a New Tag</h2>
<form action="/labels/new/" method="post"  enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

templates/labels/tag_list.html
{% extends "base.html" %}

{% block content %}
{% include "labels/nav_bar.html" %}
<h2>All Labels</h2>
<div>
{% for tag in object_list %}
<strong>{{tag.name}}</strong> v{{tag.tagversion_set.all.0.version_num}} by {{tag.author}}  Entered: {{tag.entered}}
   <form action="/labels/print/{{tag.id}}/default/">
  	<input type="submit" value="Print default tags"/>
  </form>
  <form action="/labels/print/{{tag.id}}/avery5264/">
  	<input type="submit" value="Print Avery 5264 tags"/>
  </form>
  <form action="/labels/print/{{tag.id}}/apli38/">
  	<input type="submit" value="Print apli38 tags"/>
  </form>
  <form action="/labels/edit/{{tag.id}}/">
  	<input type="submit" value="Edit"/>
  </form>
  <form action="/labels/delete/{{tag.id}}/" method="GET">
  	<input type="submit" value="Delete"/>
  </form>
  <hr />
{% endfor %}
</div>
{% endblock %}